#!/usr/bin/env bash

# Check if stdout is a terminal…
# (Copied from https://unix.stackexchange.com/a/10065 )
if test -t 1; then
  ncolors=$(tput colors)
  if test -n "$ncolors" && test $ncolors -ge 8; then
    c1_bold="$(tput bold)"
    c1_underline="$(tput smul)"
    c1_standout="$(tput smso)"
    c1_normal="$(tput sgr0)"
    c1_black="$(tput setaf 0)"
    c1_red="$(tput setaf 1)"
    c1_green="$(tput setaf 2)"
    c1_yellow="$(tput setaf 3)"
    c1_blue="$(tput setaf 4)"
    c1_magenta="$(tput setaf 5)"
    c1_cyan="$(tput setaf 6)"
    c1_white="$(tput setaf 7)"
    # (Copied from https://unix.stackexchange.com/a/174 )
    c2_nc='\e[0m' # No Color
    c2_black='\e[0;30m'
    c2_gray='\e[1;30m'
    c2_red='\e[0;31m'
    c2_light_red='\e[1;31m'
    c2_green='\e[0;32m'
    c2_light_green='\e[1;32m'
    c2_brown='\e[0;33m'
    c2_yellow='\e[1;33m'
    c2_blue='\e[0;34m'
    c2_light_blue='\e[1;34m'
    c2_purple='\e[0;35m'
    c2_light_purple='\e[1;35m'
    c2_cyan='\e[0;36m'
    c2_light_cyan='\e[1;36m'
    c2_light_gray='\e[0;37m'
    c2_white='\e[1;37m'
  fi
fi

# I) CHECK FORMAT
cargo_fmt_command="cargo fmt -- --check"

echo "${c1_bold}🔎 Checking format with '${cargo_fmt_command}'…${c1_normal}"
cargo_fmt_output="$($cargo_fmt_command 2>&1)"
if (( $? )); then
  echo "${c1_red}❌ There are some format issues. Please run 'cargo fmt'!${c1_normal}" >&2
  echo >&2
  echo "${cargo_fmt_output}" >&2
  echo >&2
  exit 1
fi

# III) CHECK LINTS

check_lints() {
  local additional_arguments="$1"

  # Standard:
  #cargo_clippy_command="cargo clippy ${additional_arguments}"
  # Warnings:
  #cargo_clippy_command="cargo clippy ${additional_arguments} -- -D warnings"
  # More:
  cargo_clippy_command="cargo clippy ${additional_arguments} -- -D warnings -D clippy::correctness -D clippy::suspicious"
  # Hell:
  #cargo_clippy_command="cargo clippy ${additional_arguments} -- -D warnings -D clippy::correctness -D clippy::suspicious -D clippy::complexity -D clippy::perf -D clippy::style -D clippy::pedantic -D clippy::restriction -A clippy::blanket-clippy-restriction-lints -D clippy::cargo"

  echo "${c1_bold}🔎 Checking lints with '${cargo_clippy_command}'…${c1_normal}"
  cargo_clippy_output="$($cargo_clippy_command 2>&1)"
  if (( $? )); then
    echo "${c1_red}❌ There are some linting issues. Please fix them!${c1_normal}" >&2
    echo >&2
    echo "${cargo_clippy_output}" >&2
    echo >&2
    exit 1
  fi
}

check_lints ""
check_lints "--no-default-features --features part1"
check_lints "--no-default-features --features part2"

# IV) CHECK TESTS

cargo_test_command="cargo test"

echo "${c1_bold}🔎 Checking tests with '${cargo_test_command}'…${c1_normal}"
cargo_test_output="$($cargo_test_command 2>&1)"
if (( $? )); then
  echo "${c1_red}❌ There are some testing issues. Please fix them!${c1_normal}" >&2
  echo >&2
  echo "${cargo_test_output}" >&2
  echo >&2
  exit 1
fi

# V) CHECK DEPENDENCIES

# Audit:
#cargo_dependencies_command="cargo audit"
# Deny:
cargo_dependencies_command="cargo deny check all"

echo "${c1_bold}🔎 Checking dependencies with '${cargo_dependencies_command}'…${c1_normal}"
cargo_dependencies_output="$($cargo_dependencies_command 2>&1)"
if (( $? )); then
  echo "${c1_red}❌ There are some dependency issues. Please fix them!${c1_normal}" >&2
  echo >&2
  echo "${cargo_dependencies_output}" >&2
  echo >&2
  exit 1
fi

echo "${c1_green}${c1_bold}✔ All Fine!${c1_normal}"
